- Pods/Pods.xcodeproj/project.pbxproj
- Pods/Pods.xcodeproj/xcuserdata/carleriksson.xcuserdatad/xcschemes/Pods-PrimerSDKExample.xcscheme
- Pods/Pods.xcodeproj/xcuserdata/carleriksson.xcuserdatad/xcschemes/PrimerSDK-PrimerSDK.xcscheme
- Pods/Pods.xcodeproj/xcuserdata/carleriksson.xcuserdatad/xcschemes/PrimerSDK.xcscheme
- PrimerSDK/Core/UI/ViewModels/ConfirmMandateViewModel.swift
- PrimerSDK/Core/UI/Views/ConfirmMandate/ConfirmMandateViewController.swift
- PrimerSDK/Core/UI/Views/Success/SuccessViewController.swift
- PrimerSDKExample/Views/CheckoutViewController.swift
CHE-
Improve error feedback mechanism and fix onTokenizeSuccess callback bug for direct debit.
...
_QA_
> [CHE-274] fix onTokenizeSuccess callback bug

- Sources/PrimerSDK/Classes/User Interface/Vault/VaultPaymentMethodViewController+TableView.swift
CHE-556
This PR removes "Add new card" button from the vault manager in the Universal Checkout.
When deleting the last vaulted payment method, this PR goes back to the Universla Checkout.
If we ship the vault manager as a standalone module, we would need to implement a proper empty screen. But we can do that for another ticket.
_QA_
> [CHE-556] Remove "Add new card" button from vault manager

- Sources/PrimerSDK/Classes/User Interface/Form/FormView.swift
CHE-557
Hide the card scan button behind a flag
Maybe there's better way to do that?
_QA_
> [CHE-557] Hide card scan button

- Example/PrimerSDK/Base.lproj/Main.storyboard
- Example/PrimerSDK/MerchantCheckoutViewController.swift
- Example/PrimerSDKExample_UITests/Base.swift
- Sources/PrimerSDK/Classes/User Interface/OAuth/WebViewController.swift
CHE-654
Test that the Klarna webview is presented.
Test that it includes the `Continue` button when it's loaded.
n/a
_QA_
> Feature/che 654 klarna UI tests

- Example/PrimerSDK.xcodeproj/project.pbxproj
- Sources/PrimerSDK/Classes/User Interface/OAuth/OAuthViewController.swift
- Tests/PrimerSDK_Tests/Mocks/Mocks.swift
- Tests/PrimerSDK_Tests/Mocks/ViewModels/OAuthViewModel.swift
- Tests/PrimerSDK_Tests/ViewControllers/OAuthViewControllerTests.swift
CHE-798
When the developer has not disabled error UI, the error view is shown on error.
The scroll view acts weird in the simulator. Let's discuss below.
Also, let's discuss ways to write a UI test for this scenario. It's been tested on live device for both PayPal & Klarna but testing requires tinkering with the example app config files we pass in on init.
_QA_
> [CHE-798] Show error message for failed PayPal init

- Example/Podfile.lock
- Example/Pods/Local Podspecs/PrimerSDK.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist
- Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist
- Example/PrimerSDK.xcodeproj/xcshareddata/xcschemes/PrimerSDK-Example.xcscheme
- Example/PrimerSDK/CreateClientToken.swift
- Example/PrimerSDK/MerchantCheckoutViewController.swift
- Sources/PrimerSDK/Classes/Core/Payment Services/ApplePayService.swift
- Sources/PrimerSDK/Classes/Core/Payment Services/PaymentMethodConfigService.swift
- Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfig.swift
- Sources/PrimerSDK/Classes/User Interface/Checkout/VaultCheckoutViewController.swift
CHE-911
https://primerapi.atlassian.net/browse/CHE-911
Fixes a bug that causes payment methods to not load after a payment method type unknown to the SDK has been added to the config.
The fix address the above scenario and filters all payment methods that have not been explicitly enabled for the SDK.
Test this by trying to load the different payment flows in the test app.
_QA_
> [CHE-911] Fix payment method config bug

- Sources/PrimerSDK/Classes/Services/API/Primer/PrimerAPI.swift
DEX-204
Adds framework version on headers
n/a
On the debugger or on data dog
_QA_
> DEX-204 Add framework version on headers

- Sources/PrimerSDK/Classes/User Interface/Root/PrimerCardFormViewController.swift
DEX-855
Present keyboard when card form gets presented.
_QA_
> DEX-855 Make cardnumber field the first responder

- Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift
DEX-855 Throw error when trying to present payment method that hasn't been configured on the dashboard.
_QA_
> DEX-855 Throw error when trying to present payment method that hasn't been configured on the dashboard.

- Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfig.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerFormViewController.swift
DEX-1038
- Hide surcharge boxes if not enabled
_QA_
> Add logic to hide surcharge boxes if no surcharge is applied

- PrimerSDK.podspec
- Sources/PrimerSDK/Classes/Extensions & Utilities/UserDefaultsExtension.swift
- React Native uses its own bundle, fallback to standard user defaults if the SDK bundle is not found
> Hotfix Fallback to standard user defaults in case of RN

- Sources/PrimerSDK/Classes/Data Models/Currency.swift
Adding `VND` currency code the list of zeroDecimal
_QA_
> DEX-1649 Added VND to isZeroDecimal

- PrimerSDK.podspec
- Sources/PrimerSDK/Classes/Data Models/PaymentMethodTokenizationRequest.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PayPalTokenizationViewModel.swift
Release 1.35.0
- Fix vaulting with PayPal
- Remove `customerId` on tokenization API call on latest API version
- Return an error when vaulting if `customerId` doesn't exist in the client session
> Release 1.35.0

- Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift
There was an issue in the result view always showing the success screen I spotted while running tests.
This PR addresses the issue.
> Passing correct screen type to result screen

- Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckoutProtocols.swift
- Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawDataManager.swift
- Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawPhoneNumberDataTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/StringExtension.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift
- Adding the `ADYEN_MBWAY` raw data support similar to the implementation done for supporting `XENDIT_OVO`.
- The phone number validation has been reviewed to accommodate a simplified set of validations based on the PaymentMethodType and quickly sort out our needs.
> DEX-2361 MBWay Headless Raw Support

- Sources/PrimerSDK/Classes/Data Models/Klarna.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
Replace `hppRedirectUrl` with `urlScheme`
Co-authored-by: Evangelos Pittas <evangelos@primer.io>
DEVX-205
_QA_
> DEVX-205 Replace Klarna redirect URL (#485)

- Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawPhoneNumberDataTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawRetailerDataTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataRedirectTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift
Fixing the `delegate` reference on the `RawDataTokenziationBuilder`s
Fixes also a React Native issue: 
- `Await HeadlessUniversalCheckoutRawDataManager.setRawData(cardData)` never results in the `onValidation callback`
> DEX-2494  Fix delegate issue on Tokenization builder

- Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift
- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift
This PR fixes the issue on the cardholder name check against the checkout module configuration.
In the case of a non-present checkout module, by default, it adds the cardholder name among the required fields.
The PR also fixes the required fields array not returned out of the `public func listRequiredInputElementTypes(for paymentMethodType: String) -> [PrimerInputElementType]?`
> DEX-2494 Card holder name fix

- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PayPalTokenizationViewModel.swift
Fixing the PaypalService, so that the `PaypalTokenizationViewModel`relies on a single instance of the PaypalService to both `startBillingAgreementSession(:)` and `confirmBillingAgreement(:)`
> DXS-127 Fix Paypal service

- Sources/PrimerSDK/Classes/Data Models/CountryCode.swift
- Sources/PrimerSDK/Classes/User Interface/Banks/BankSelectorViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Countries/CountrySelectorViewController.swift
Improvements in the Banks and Countries selector.
As you can navigate back and forth in Banks, we don't want a new object added to memory every time we present the list.
We have removed the warning in the console attempting to present the countries list.
> CHKT-266 Improvements on the Bank and Country selector

- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel.swift
There was no strong reference to the config so ARC was cleaning it up.
> FIx Apple Pay crash

- .github/workflows/build_test_upload.yml
- Internal/Debug App/Tests/Unit Tests/Primer/PrimerBancontactCardDataManagerTests.swift
- Internal/Debug App/Tests/Unit Tests/Primer/PrimerRawCardDataManagerTests.swift
- Internal/Debug App/Tests/Unit Tests/Primer/PrimerRawRetailerDataTests.swift
- Internal/Debug App/Tests/Unit Tests/v2/HeadlessVaultManagerTests.swift
- Internal/Debug App/Tests/Unit Tests/v2/RawDataManagerTests.swift
- fastlane/Fastfile
This PR adds running of the Debug App's Unit Test target before the Appetize build step.
Changes made to the unit tests:
- Moved an incorrectly placed expectation fulfill in `HeadlessVaultManager.test_headless_delete_vaulted_payment_method`
- Flipped an assertion (see comment in file)
- Updated expectation timeouts where the value was too low for the slower build machine
> Run unit tests during pipeline build

- Internal/Debug App/Tests/Unit Tests/Modules/HUC_TokenizationViewModelTests.swift
- Internal/Debug App/Tests/Unit Tests/Modules/PollingModuleTests.swift
- Internal/Debug App/Tests/Unit Tests/v2/MockAPIClient.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/WebRedirectPaymentMethodTokenizationViewModel.swift
CHKT-1636
Removes `PollingURLs` from `PollingResponse` per conversation with @xevious78.
_QA_
> Remove PollingURLs from PollingResponse

- Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
- Debug App/Tests/Unit Tests/Utils/VersionUtilsTests.swift
- Sources/PrimerSDK/Classes/Core/Analytics/Analytics.swift
- Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsEvent.swift
- Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/BundleExtension.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/VersionUtils.swift
- Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift
- Replaces all usage of `info.plist` for version reporting with the new `version.swift`
- Added a utility to wrap this number to preserve current react native version logic
- Added unit tests to this utility
_QA_
> chore: use version.swift file

- .github/workflows/create-release.yml
We cannot create a new branch named `release` because `release/xx` branches exist.
` ! [remote rejected]   release -> release (cannot lock ref 'refs/heads/release': 'refs/heads/release/2.13.2'`
https://github.com/primer-io/primer-sdk-ios/actions/runs/6325635960/job/17177564321
> fix: release workflow - update branch name

- Dangerfile.swift
This PR adds a failure when a [commitizen-compatible conventional commit](https://www.notion.so/primerio/Automating-Version-Bumping-and-Changelog-Creation-c13e32fea11447069dea76f966f4b0fb?pvs=4#c55764aa2f2748eb988d581a456e61e7) prefix is not used for the PR title.
Example of failure:
> chore: Danger fails when conventional commit title is not used

- Sources/PrimerSDK/Classes/Core/3DS/Mock/Mock3DSService.swift
This PR fixes this issue: https://github.com/primer-io/primer-sdk-ios/issues/695 
We will add an SPM build step to the CI pipeline in another PR
Test this in an SPM-integrated app
_QA_
> fix: Add UIKit import to Mock3DSService.swift

- Gemfile
- Gemfile.lock
Addressing the failure on gitlab CI.
See this SO answer: https://stackoverflow.com/questions/77236339/after-updating-cocoapods-to-1-13-0-it-throws-error
Cocoapods issue: https://github.com/CocoaPods/CocoaPods/issues/12081
> chore: Use last stable version of activesupport

- Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
- Debug App/Tests/Unit Tests/Mocks.swift
- Debug App/Tests/Unit Tests/Mocks/Services/NetworkService.swift
- Debug App/Tests/Unit Tests/Network/ListCardNetworksEndpointTests.swift
- Debug App/Tests/Unit Tests/v2/MockAPIClient.swift
- Sources/PrimerSDK/Classes/Data Models/Bin.swift
- Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift
- Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift
CHKT-1751
* Adds the new endpoint based on the open API spec to the Primer API service
* Adds tests for the new endpoint
* Introduces some new networking mocks that allow appropriate testing 
We were using a mix of `Timer.scheduledTimer` and `DispatchQueue.main.async` across the mocks, and not consistently in any one place. I've replaced them all with `DispatchQueue.main.asyncAfter`
_QA_
> chore: Add card networks endpoint to network and API services

- .github/workflows/build_test_upload.yml
- Debug App/Podfile.lock
CHKT-1683
Ensures existing jobs are cancelled when starting a new job, regardless of trigger reason (pull request, edit, etc.)
> chore: Add concurrency gate to app build workflow

- Debug App/Tests/Unit Tests/Analytics/AnalyticsTests.swift
- Sources/PrimerSDK/Classes/Core/Analytics/Analytics.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/BundleExtension.swift
CHKT-1683
Reports the minimum deployment target (i.e. min required OS version) of the integrating app.
Inspect the event at runtime
_QA_
> chore: Report min deployment version as semver string with every event

- .github/workflows/ui-tests.yml
- fastlane/Fastfile
Removes the stipulation that Slack reports are only sent for PRs pointing to master
> chore: Ensures ui test slack reports are sent even when not on PR

- Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
- Debug App/Tests/Unit Tests/Extensions/StringExtensionTests.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Models/PrimerHeadlessUniversalCheckoutInputElement.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/StringExtension.swift
- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataRedirectTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/PCI/User Interface/Text Fields/PrimerCardholderNameFieldView.swift
- Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerCityFieldView.swift
- Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerFirstNameFieldView.swift
- Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerLastNameFieldView.swift
- Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerStateFieldView.swift
DEX-
* Remove unused String extension functions and properties
* Remove String extension functions and properties that are duplicates of other functions and properties 
* Add unit tests for majority of remaining methods
_QA_
> chore: Clean up string extension + add unit tests

- Debug App/Primer.io Debug App SPM.xcodeproj/project.pbxproj
- Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
- Debug App/Resources/Localized Views/Base.lproj/Main.storyboard
- Debug App/Sources/Network/Networking.swift
- Debug App/Sources/Network/URL+NetworkHeaders.swift
- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Debug App/Tests/Unit Tests/Network/NetworkTests.swift
[TWS-37](https://primer-ext.atlassian.net/browse/TWS-37)
As a developer of the primer iOS SDK the Debug App
I want to be able to see a toggle labelled “Enable New Workflows“ 
So that I can switch to using the new workflows for the session creation.
Other clients, eg: Android and Web have this toggle/checkbox.
Add Toggle UI inside the Debug App Setup Screen for the “Create Session” Tab.
Default toggle state is off
When toggle is on, the request for /client-session contains the HTTP header Legacy-Workflows: false
When toggle is off, the request for /client-session contains doesn’t contain the HTTP header Legacy-Workflows
Toggle state doesn’t affect any other HTTP requests on different methods
Payments are successful under the new workflows for iDeal under development environment when toggle …
> chore: Add toggle in the Debug application for Legacy-Workflows at session creation

- Debug App/Sources/View Controllers/New UI/MerchantHeadlessCheckoutNolPayViewController.swift
- Debug App/Tests/Unit Tests/Primer/NolPay/NolPayLinkCardComponentTest.swift
- Debug App/Tests/Unit Tests/Primer/NolPay/NolPayPaymentComponentTests.swift
- Debug App/Tests/Unit Tests/Primer/NolPay/NolPayUnlinkCardComponentTest.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayLinkCardComponent.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayPaymentComponent.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayUnlinkCardComponent.swift
This PR fixes a bug with Nol state machine. If a user wants to change the phone number after sending it for validation an error is returned. `submit()` was handling wrong step.
[JIRA](https://primerapi.atlassian.net/browse/CHKT-1928)
[SLACK](https://primerapi.slack.com/archives/C05DJ5LV309/p1699871603945539)
> fix: Fix state machine to allow going back in steps

- Debug App/Sources/View Controllers/New UI/MerchantHeadlessCheckoutNolPayViewController.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayPhoneMetadataService.swift
We were not checking against an empty string before sending the phone string to the server for validation. Server returned 404 if you send it empty string.
> fix: Add local empty phone validation

- Debug App/Tests/Unit Tests/Services/CardValidationServiceTests.swift
- Debug App/Tests/Unit Tests/Test Utilities/StringTyper.swift
- Sources/PrimerSDK/Classes/Core/BIN Data/CardValidationService.swift
CHKT-1885
Previously we triggered debounced validation on 6-8 characters, now we will trigger it:
1. When less than eight digits are entered, on eighth digit being entered 
2. After eight digits have been entered, only if the first eight digits change.
* The first request is no longer debounced to ensure that we make an early request for the most common use case (i.e. straight entry without user error)
_QA_
> chore: Constrain remote validation logic to eight-digit BIN only

- .github/workflows/post-release-merge.yml
The workflow didnt run as expected yesterday. I did some testing on [another repo](https://github.com/NQuinn27/TestActions) and this syntax will get us where we want to be,
The workflow will run if:
- a PR is **closed** and **merged**
- the head_ref is `release/next`
> chore: Correct syntax for post-pr merge

- Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
- Debug App/Sources/AppDelegate.swift
- Debug App/Tests/Unit Tests/Analytics/AnalyticsServiceTests.swift
- Debug App/Tests/Unit Tests/Analytics/AnalyticsStorageTests.swift
- Debug App/Tests/Unit Tests/Analytics/AnalyticsTests+Helpers.swift
- Debug App/Tests/Unit Tests/Analytics/AnalyticsTests.swift
- Debug App/Tests/Unit Tests/Helpers/Promises+Helper.swift
- Debug App/Tests/Unit Tests/Network/URLSessionStackTests.swift
- Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift
- Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsStorage.swift
- Sources/PrimerSDK/Classes/Core/Primer/PrimerDelegate.swift
- Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/PrimerHeadlessUniversalCheckout.swift
- Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift
- Sources/PrimerSDK/Classes/Services/Network/Protocols/PrimerAPIClientAnalyticsProtocol.swift
CHKT-1963
Rework of the analytics service
1. Refactor service to simplify use of concurrency and promises
2. Ensure batches are sent once a limit is reached (currently 100 events)
3. Split service into isolated storage and reporting services
Run debug app, filter console on "Analytics", then go through drop-in or headless checkout
> fix: Reduce memory usage for analytics service

- Sources/PrimerSDK/Classes/Error Handler/PrimerValidationError.swift
Adds missing equatable conformance to new `PrimerValidationErrors` `.banksNotLoaded` and `.invalidBankId`
> chore: Add equatable conformance to new PrimerErrors

- Debug App/Tests/Unit Tests/Network/URLSessionStackTests.swift
- Debug App/Tests/Unit Tests/v2/RawDataManagerTests.swift
- Sources/PrimerSDK/Classes/Core/BIN Data/CardValidationService.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/AssetsManager.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Models/PrimerCardValidationModels.swift
- Sources/PrimerSDK/Classes/Data Models/CardNetwork.swift
- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift
- Sources/PrimerSDK/Classes/PCI/Services/Network/URLSessionStack.swift
- Sources/PrimerSDK/Classes/Services/Network/Endpoint.swift
CHKT-2124
- Remove local-only network type validation for cards
- Priotitise remote/fallback network type validation over card number format validation 
- Update tests
- Removed `getAllowedCardNetworkAssets` - we will add a different solution post-v1
- More reliable local display name for cards
- 10s timeout for BIN data requests
> chore: DX alignment for co-badged cards

- Debug App/Sources/View Controllers/MerchantDropInUIViewController.swift
- Debug App/Tests/Unit Tests/Extensions/StringExtensionTests.swift
- Debug App/Tests/Unit Tests/Mocks.swift
- Debug App/Tests/Unit Tests/Primer/NolPay/NolPayLinkCardComponentTest.swift
- Debug App/Tests/Unit Tests/Primer/NolPay/NolPayLinkedCardsComponentTests.swift
- Debug App/Tests/Unit Tests/Primer/NolPay/NolPayUnlinkCardComponentTest.swift
- Debug App/Tests/Unit Tests/Primer/NolPay/NolTestsMocks.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayLinkedCardsComponent.swift
- Sources/PrimerSDK/Classes/Data Models/PaymentMethod.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerFormViewController.swift
Make sure fetching of the card is being called after fetching of the secret key is finished
[CHKT-2121](https://primerapi.atlassian.net/browse/CHKT-2121)
- Fix a bug in the case where fetching of the cards was called right after init() of the NolPayLinkedCardsComponent.
Fetching of the card was called before fetching the nolSdk secret key from the backend, I added these two requests into the DispatchGroup() 
There were no changes in the public nol API and no changes in the documentation are needed.
- You can find out more about our automation checks …
> fix: Fix NOL pay bug - fetching of the cards

- Dangerfile.swift
- Debug App/Tests/Unit Tests/Extensions/StringExtensionTests.swift
This adds more allowed conventional commit titles to the danger checks. Valid examples taken from the commitizen guides:
> ci: Add more conventional commit titles

- Debug App/Podfile.lock
- Sources/PrimerSDK/Classes/version.swift
CHKT-2191
Publicise the `PrimerSDKVersion` constant so that it can be used by the react native SDK / other integrations.
> build: Publicise version constant

- .github/pull_request_template.md
> chore: Remove manual checklist requirement for conventional commit title

- Debug App/Tests/Unit Tests/v2/MockAPIClient.swift
- Sources/PrimerSDK/Classes/Core/Models/BanksTokenizationComponent.swift
- Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift
- Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClientProtocol.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/BankSelectorTokenizationViewModel.swift
[TWS-231](https://primer-ext.atlassian.net/browse/TWS-231)
Fix for retrieve banks request that is failing to decode.
> fix: Adyen IDeal banks request failing

- Debug App/ExampleApp.entitlements
This PR adds Apple Pay merchant IDs for acceptance team in all environments
> chore: add acceptance merchant Ids

- Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift
- Sources/PrimerSDK/Classes/Core/Primer/PrimerDelegate.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/PrimerHeadlessUniversalCheckoutProtocols.swift
To avoid a breaking change due to a typo in a method name add the method with a proper name and deprecation of the old one.
> chore: Deprecate a delegate method with a typo and add a new one with a proper name

- Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsEvent.swift
- Sources/PrimerSDK/Classes/PCI/Services/DefaultNetworkService.swift
- Sources/PrimerSDK/Classes/PCI/Services/Network/NetworkReportingService.swift
- Tests/Primer/Network/Services/NetworkingReportingServiceTests.swift
[ACC-3668](https://primerapi.atlassian.net/browse/ACC-3668)
Adds duration tracking to `NETWORK_CALL_EVENT` `REQUEST_END` events.
Events can be inspected [here](https://primer-monitoring.kb.eu-west-1.aws.found.io:9243/s/checkout/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-30m,to:now))&_a=(columns:!(SDK.sdkType,SDK.properties.duration),filters:!(),index:'5a2c0d71-d670-455b-bb55-9442e9c76eb3',interval:auto,query:(language:kuery,query:'SDK.properties.duration:%20*%20AND%20SDK.sdkType%20:%20%22IOS_NATIVE%22%20'),sort:!(!('@timestamp',desc))))
- You can find …
> fix: Add duration tracking for network requests

- Sources/PrimerSDK/Classes/Core/Primer/Primer.swift
- Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/PrimerHeadlessUniversalCheckout.swift
- Tests/Primer/Utils/CheckoutSessionTests.swift
CHKT-XXXX
- These changes expose `Primer.shared.checkoutSessionIsActive`
- This will indicate if there is an active session.
- Merchant must use the `PrimerHeadlessUniversalCheckout.cleanUp()` function to rely on this.
> feat: session is active

- .cz.toml
- CHANGELOG.md
- PrimerSDK.podspec
- Sources/PrimerSDK/Classes/version.swift
> Release 2.28.0

- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Models/PrimerHeadlessUniversalCheckoutPaymentMethod.swift
- Tests/Primer/Data Models/PrimerPaymentMethodTests.swift
- fastlane/Fastfile
Background: a merchant developer would like to create `PrimerHeadlessUniversalCheckout.PaymentMethod`s in their test suite. Our current initializer did not allow this, as it relied on the side effect of `PrimerAPIConfiguration` providing a `PrimerPaymentMethod` to back the `PrimerHeadlessUniversalCheckout.PaymentMethod`.
Two solutions are presented here:
1. Injected the `PrimerPaymentMethodProviding` object, implemented a default in `PrimerHeadlessUniversalCheckout.PaymentMethod` to perform the current behaviour.
2. Surfaced an initializer only in DEBUG builds to allow direct creation of the `PrimerHeadlessUniversalCheckout.PaymentMethod` directly
> chore: Enable PrimerHeadlessUniversalCheckout.PaymentMethod creation for tests

- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/PrimerHeadlessUniversalCheckout.swift
- Tests/Primer/Utils/CheckoutSessionTests.swift
[ACC-3935](https://primerapi.atlassian.net/browse/ACC-3935)
the uiDelegate property when starting the headless is ignored in the function. Setting it afterward directly works 
[ACC-3935]: https://primerapi.atlassian.net/browse/ACC-3935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: apply uiDelegate when set in PrimerHeadlessUniversalCheckout.current.start

- Sources/PrimerSDK/Classes/Services/Network/WebAuthenticationService.swift
Utility for getting key window was not honoring window order - this ensures the current top-of-stack window is taken.
> fix: Ensure paypal webview is displayed on correct window

- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
- Tests/Primer/Extensions/ErrorExtensionTests.swift
- Tests/Primer/Tokenization/View Models/CardFormPaymentMethodTokenizationViewModelTests.swift
[DPS-615](https://primerapi.atlassian.net/browse/DPS-615)
- Adds `PrimerCheckoutData` with a `paymentId` to the callback in the case of error.
This unblocks the merchant, but we will create a ticket to build a more robust solution which returns the actual response, and aligns with Android.
In the Debug App, perform a PayPal payment (on Headless) - it should fail and allow you to inspect the callback.
[DPS-615]: …
> fix: Add some checkoutData in the case of error

- Sources/PrimerSDK/Classes/Core/Payment Services/CreateResumePaymentService.swift
- Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
- Tests/Primer/Extensions/ErrorExtensionTests.swift
- Tests/Primer/Tokenization/View Models/CardFormPaymentMethodTokenizationViewModelTests.swift
Small enhancement to also add the `orderId` to the error context
> fix: Adds orderId to the PrimerCheckoutData in error case

- .github/actions/ui-tests/action.yml
- .github/workflows/ui-tests.yml
This pulls the secrets API key into UI tests config
> ci: Add secrets key to e2e tests

- Debug App/Podfile.lock
- Sources/PrimerSDK/Classes/User Interface/ApplePayPresentationManager.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
- Tests/Primer/Tokenization/View Models/ApplePayTokenizationViewModelTests.swift
There are currently two checks for whether Apple Pay can be presented, one in inside `ApplePayPresentationManager` and the other outside wrapping the call to `present` on the manager.
Only the former reports a presentation error on failure to show the Apple Pay dialog. This is never reached due to the outer wrap.
This PR removes the inner check and reports the error if the remaining check fails.
> fix: Fix error reporting for apple pay display failure

- Sources/PrimerSDK/Classes/Core/Cache/ConfigurationCache/ConfigurationCache.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/PrimerHeadlessUniversalCheckout.swift
[PRMSUP-2746](https://primerapi.atlassian.net/browse/PRMSUP-2746)
This one I couldnt reproduce well, but I believe these changes will help guard against the kinds of crashes in the ticket.
[PRMSUP-2746]: https://primerapi.atlassian.net/browse/PRMSUP-2746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> fix: Add additional rails to guard against crashes

- Debug App/Resources/Localized Views/Base.lproj/Main.storyboard
- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Sources/PrimerSDK/Classes/Data Models/API/PaymentAPIModel.swift
- Sources/PrimerSDK/Classes/Data Models/ClientSession.swift
- Sources/PrimerSDK/Classes/Data Models/_PaymentAPIModel.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
- Tests/Klarna/KlarnaTestsMocks.swift
- Tests/Primer/Data Models/ApplePayTests.swift
- Tests/Primer/Tokenization/View Models/ApplePayTokenizationViewModelTests.swift
- Tests/Primer/UI/ACHUserDetails/ACHUserDetailsViewControllerTests.swift
- Tests/Primer/v2/HeadlessUniversalCheckoutAPIConfigurationTests.swift
- Tests/Primer/v2/HeadlessVaultManagerTests.swift
- Tests/Primer/v2/RawDataManagerValidationTests.swift
- Tests/Stripe/ACHMocks.swift
- Tests/Stripe/StripeAchTokenizationViewModelTests.swift
- Tests/Utilities/Mocks/Services/MockAPIClient.swift
Final tweaks for Apple Pay Express Checkout:
- Remove the shipping method name from the lineItems display.
- Align errors
- Adds Shipping to PrimerOrder object
Updates the Debug App to allow more granular testing of Apple Pay Shipping controls
> fix: Apple Pay EC Updates

- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
Fixes incorrect reporting of timed out payments. Setting `didTimeout=false` here feels correct since authorization should be the final callback handler in the flow.
> fix: Apple Pay incorrect timeout reporting

- Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/Payment Method Managers/RawDataManager.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/PrimerRawOTPDataTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/Data Models/PrimerPaymentMethod.swift
- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerOTPData.swift
- Tests/Primer/Data Models/PrimerPaymentMethodTests.swift
- Tests/Primer/Managers/PrimerOTPDataTests.swift
- Tests/Primer/Managers/PrimerRawOTPDataTokenizationBuilderTests.swift
[JIRA](https://primerapi.atlassian.net/browse/ACC-4219)
> feature: Add Adyen Blik to Headless

- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
- Remove the `PrimerApplePayOptions.ShippingOptions` from public interface to facilitate EC beta
> chore: Remove PrimerApplePayOptions.ShippingOptions from public interface

- Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/CardFormPaymentMethodTokenizationViewModel.swift
[CHKT-4038](https://primerapi.atlassian.net/browse/ACC-4038)
> fix: Prevent dismissal of Drop-in card form while a payment is active

- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/AssetsManager.swift
- Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/VaultManager.swift
- Tests/Primer/Assets/AssetsManagerTests.swift
CHKT-XXXX
- Makes initialiser for VaultedPaymentMethod public.
- Adds convenience initialiser for CardNetworkAsset from network string
> fix: Expose VaultedPaymentMethod initialiser

- Debug App/Podfile.lock
- Package.3DS.swift
- Package.swift
Updates the versions of PrimerSDK and Primer3DS dependencies in the Debug App.
This also updates the 3DS dependency in the Package.swift which requires a release
> fix: Update 3DS SDK and PrimerSDK Versions

- Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift
[ESC-202](https://primerapi.atlassian.net/browse/ESC-202)
- Replaces the precondition with a logged error and graceful failure
[ESC-202]: https://primerapi.atlassian.net/browse/ESC-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Remove precondition on presentPaymentMethod

- fastlane/Fastfile
Updates logic to migrate from LiveDemoStore to the new demo
> chore: Migrate Appetize previews to new demo

- Sources/PrimerSDK/Classes/User Interface/Components/PrimerResultViewController.swift
[ACC-4058](https://primerapi.atlassian.net/browse/ACC-4058)
[ACC-4058]: https://primerapi.atlassian.net/browse/ACC-4058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Make success asset visible In dark mode

- Sources/PrimerSDK/Classes/Core/Constants/Colors.swift
[ACC-4059](https://primerapi.atlassian.net/browse/ACC-4059)
In dark mode, bottom sheet should be more prominent so I updated the color as Sau suggested in the Jira ticket.
[ACC-4059]: https://primerapi.atlassian.net/browse/ACC-4059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Update the default background color of the default theme for dark mode

- Debug App/Podfile.lock
- Debug App/Sources/View Controllers/MerchantHeadlessVaultManagerViewController.swift
- Sources/PrimerSDK/Classes/Data Models/TokenizationResponse.swift
- Tests/Primer/v2/HeadlessVaultManagerTests.swift
- Tests/Utilities/Mocks.swift
This changes accountNumberLastFourDigits to accountNumberLast4Digits to align with Android, and adds the output to the Headless Vault Example
> fix: Align accountNumberLast4Digits with Android

- Debug App/Podfile.lock
- Debug App/Resources/Localized Views/Base.lproj/Main.storyboard
- Debug App/Sources/Network/Networking.swift
- Debug App/Sources/View Controllers/MerchantDropInUIViewController.swift
- Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift
- Debug App/Sources/View Controllers/MerchantHeadlessVaultManagerViewController.swift
- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
- Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift
- Tests/Primer/Network/Endpoints/ListCardNetworksEndpointTests.swift
- Tests/Primer/Network/Factories/NetworkRequestFactoryTests.swift
- Tests/Primer/UI/PrimerInputElementTests.swift
- Tests/Utilities/Mocks.swift
[ACC-4831](https://primerapi.atlassian.net/browse/ACC-4831)
- Adds `apiVersion` to `PrimerSettings`
- Adds logic to default to version 2.3 for now
- Adds ability to choose apiVersion in Debug app for SDK and ClientSession creation
[ACC-4831]: https://primerapi.atlassian.net/browse/ACC-4831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add apiVersion to PrimerSettings

- Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift
[JIRA](https://primerapi.atlassian.net/browse/ACC-4693)
New values:
Path | iOS Host | Timeout
-- | -- | --
/payment-instruments/<paymentMethodId>/exchange | pciUrl | 15
/ | configurationUrl | 15
/payment-instruments | pciUrl | 15
/payment-instruments/\\(id)/vault | pciUrl | 15
/payment-instruments | pciUrl | 15
/client-session/actions | pciUrl | 15
/3ds/<paymentMethodToken.token>/auth | pciUrl | 15
/3ds/<threeDSTokenId>/continue | pciUrl | 15
/client-token/validate | request.clientToken.decodedJWTToken?.pciUrl | 15
/payments | pciUrl | 15
/sdk/payments | NOT USED | 15
/payments/<paymentd)/resume | pciUrl | 15
/v1/bin-data/\\(bin)/networks | binDataUrl | 15
/paypal/orders/create | coreUrl | 60
/paypal/billing-agreements/create-agreement | coreUrl | 60 …
> chore: Update API timeout values

- Debug App/Podfile.lock
- Debug App/Resources/Localized Views/Base.lproj/Main.storyboard
- Debug App/Sources/Network/Networking.swift
- Debug App/Sources/View Controllers/MerchantDropInUIViewController.swift
- Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift
- Debug App/Sources/View Controllers/MerchantHeadlessVaultManagerViewController.swift
- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
- Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift
- Tests/Primer/Network/Endpoints/ListCardNetworksEndpointTests.swift
- Tests/Primer/Network/Factories/NetworkRequestFactoryTests.swift
- Tests/Primer/UI/PrimerInputElementTests.swift
- Tests/Utilities/Mocks.swift
[CHKT-4444](https://primerapi.atlassian.net/browse/ACC-4444)
> feat: Update to API version 2.4

- Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
Since we run Swiftlint via Danger on every PR, it is not needed to re-run it again on every build on CI.
Swiftlint will run as normal on local builds, and provide in-editor feedback
> chore: Skip swiftlint on CI

- Debug App/Sources/Network/Networking.swift
- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
- Tests/Utilities/Mocks.swift
We are misaligned with Android here, changes `PrimerAPIVersion` -> `PrimerApiVersion`
> chore: Align PrimerApiVersion with Android

- .gitignore
Updates .gitignore to ignore files generated by neovim, xcodebuild.nvim, avante.nvim, Cursor and VSCode editors.
> chore: Update .gitignore to ignore files generated by other editors

- Sources/PrimerSDK/Classes/Core/Constants/Strings.swift
- Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/CardFormPaymentMethodTokenizationViewModel.swift
- Sources/PrimerSDK/Classes/PCI/User Interface/Text Fields/PrimerCardholderNameFieldView.swift
[JIRA](https://primerapi.atlassian.net/browse/ACC-4661)
> chore: Align cardholder name validation with Web

- Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift
CHKT-XXXX
- These changes update the /resume and /payment endpoint timeouts to 60s
> fix: Update /payment and /resume timeouts to 60s

- Debug App/Primer.io Debug App SPM.xcodeproj/project.pbxproj
This was the source of the packages constantly resolving. Now 3DS is in the main SDK, adding it also to the Debug App caused a circular dependency
> chore: Remove 3ds package from Debug App

- Debug App/Podfile.lock
- Sources/PrimerSDK/Classes/Core/Payment Services/CreateResumePaymentService.swift
- Sources/PrimerSDK/Classes/PCI/Services/Network/Factories/NetworkResponseFactory.swift
- Tests/Primer/Network/Factories/NetworkResponseFactoryTests.swift
[ESC-341](https://primerapi.atlassian.net/browse/ESC-341)
For certain 2xx responses (e.g., 202), the API may return an error object instead of the expected response.  
Previously, we threw a `failed-to-decode` error in such cases.  
Now, we'll attempt to decode the error response and propagate it upstream. We'll propagate `failed-to-resume` error in case resume fails from now on with proper underlying error.
To reproduce, set `is3DSSanityCheckEnabled` to `false`.
[ESC-341]: …
> fix: Decode errors properly for 2xx response codes

- Debug App/Sources/Network/Networking.swift
- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
- Tests/Primer/Network/Endpoints/ListCardNetworksEndpointTests.swift
- Tests/Primer/Network/Factories/NetworkRequestFactoryTests.swift
- Tests/Utilities/Mocks.swift
[ACC-5212](https://primerapi.atlassian.net/browse/ACC-5212)
- Updates default API Version from 2.3 to 2.4
[ACC-5212]: https://primerapi.atlassian.net/browse/ACC-5212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Update default api version to 2.4

- Sources/PrimerSDK/Classes/Core/3DS/3DSService.swift
Functionally equivalent code.
This fixes SwiftLint complaining about cyclomatic complexity (seen [here](https://github.com/primer-io/primer-sdk-ios/pull/1158#issuecomment-2858166830)) and makes the function slightly easier to reason about
Tests results remain the same
> refactor: Modularise Primer3DS initialisation

- Debug App/Info.plist
- Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
- Debug App/Sources/AppDelegate.swift
- Debug App/Sources/Utilities/AppLinkConfigProvider.swift
- Debug App/Sources/Utilities/TestHelper.swift
Adds DeepLinking support for existing UniversalLinks. This speeds up E2E test execution by removing the need to paste in values for ClientToken and Settings.
Sample [Link](primer://sdk-demo.primer.io/latest/iOS?clientToken= eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImNsaWVudC10b2tlbi1zaWduaW5nLWtleSJ9.eyJleHAiOjE3NDc3Mzc4NTIsImFjY2Vzc1Rva2VuIjoiZTRmMmZhNTctY2JjMS00NGViLWFiMTUtY2JiYTNiYjA4YjBlIiwiYW5hbHl0aWNzVXJsIjoiaHR0cHM6Ly9hbmFseXRpY3MuYXBpLnNhbmRib3guY29yZS5wcmltZXIuaW8vbWl4cGFuZWwiLCJhbmFseXRpY3NVcmxWMiI6Imh0dHBzOi8vYW5hbHl0aWNzLnNhbmRib3guZGF0YS5wcmltZXIuaW8vY2hlY2tvdXQvdHJhY2siLCJpbnRlbnQiOiJDSEVDS09VVCIsImNvbmZpZ3VyYXRpb25VcmwiOiJodHRwczovL2FwaS5zYW5kYm94LnByaW1lci5pby9jbGllbnQtc2RrL2NvbmZpZ3VyYXRpb24iLCJjb3JlVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5wcmltZXIuaW8iLCJwY2lVcmwiOiJodHRwczo …
> chore: Add DeepLink Handling

- .github/actions/ui-tests/action.yml
- .github/workflows/ui-tests.yml
- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
[ACC-5606](https://primerapi.atlassian.net/browse/ACC-5606)
- Upload the built app to LambdaTest
- Run UI Tests via LambdaTest
Example manual run: https://appautomation.lambdatest.com/test?build=10588189&testID=RMAA-IOS-2485053-1751984802421556566QJQ
Improvements which I would like to do, not to be tackled here:
- Break up the `ui-tests` job to separate manual and automatic runs. (See Android).
[ACC-5606]: https://primerapi.atlassian.net/browse/ACC-5606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Route UI Tests to Lambdatest

- .github/workflows/ui-tests.yml
This fixes a mistake in the previous PR which caused testType to not be correctly set for the nightly tests.
> ci: Fix incorrect test-type config

- PrimerSDK.xcworkspace/contents.xcworkspacedata
- Sources/PrimerSDK/Classes/Core/Analytics/Analytics+UIViewController.swift
- Sources/PrimerSDK/Classes/PCI/User Interface/Root/PrimerCardFormViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Banks/BankSelectorViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Components/PrimerCustomResult/PrimerCustomResultViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Components/PrimerResultViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Countries/CountrySelectorViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Root/CVVRecapture/CVVRecaptureViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerFormViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerLoadingViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerUniversalCheckoutViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Root/PrimerVaultManagerViewController.swift
- Sources/PrimerSDK/Classes/User Interface/TestPaymentMethods/PrimerTestPaymentMethodViewController.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewControllers/QRCodeViewController.swift
- Sources/PrimerSDK/Classes/User Interface/Vault/VaultPaymentMethodViewController.swift
Tidies up the instances of posting ui events by creating a method restricted to UIViewControllers which are the classes that should concern themselves with UI events. Not included as part of this is moving posting ui events from non-ui contexts, which would be a wise next step
Tests are unaffected
> refactor: Clean up UI event posting

- Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift
- Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift
📋 Ticket
https://primerapi.atlassian.net/browse/ACC-5636
🎯 Problem
Since iOS SDK v2.38.0 (Co-badged Cards implementation), we've seen a massive increase in [missing value] errors in our analytics dashboard. Investigation revealed
that validation errors are being logged on every keystroke during card form input, creating hundreds of unnecessary error events per user session.
🔍 Root Cause
The onDataDidChange callback in PrimerRawCardDataTokenizationBuilder triggers validation on every character typed. Each validation cycle finds errors for
incomplete fields (empty CVV, invalid card number, etc.) and logs them via ErrorHandler.handle(), flooding our analytics with transient validation errors.
✅ Solution
Removed ErrorHandler.handle() calls from the real-time validation path (validateRawData). …
> fix: ACC-5636 excessive validation logging

- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- PrimerSDK.xcworkspace/contents.xcworkspacedata
- Sources/PrimerSDK/Classes/Data Models/ApplePay.swift
- Sources/PrimerSDK/Classes/Data Models/ClientSession.swift
- Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationOptions.swift
- Sources/PrimerSDK/Classes/Data Models/TokenizationResponse.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/ApplePayPaymentRequest+PK.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/IntExtension.swift
- Sources/PrimerSDK/Classes/User Interface/ApplePayPresentationManager.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
- Tests/Klarna/KlarnaTestsMocks.swift
- Tests/Primer/ApplePay/ApplePayPresentationManagerTests.swift
- Tests/Primer/Extensions/ApplePay.swift
- Tests/Primer/Ideal/IdealPaymentMethodTests.swift
- Tests/Primer/Ideal/PrimerHeadlessFormWithRedirectManagerTests.swift
- Tests/Primer/Modules/HeadlessUniversalCheckoutTests.swift
- Tests/Primer/Modules/XCTestCase+Tokenization.swift
- Tests/Primer/Utils/ApplePayPaymentRequest+PK.swift
- Tests/Primer/v2/HeadlessUniversalCheckoutAPIConfigurationTests.swift
- Tests/Primer/v2/HeadlessVaultManagerTests.swift
- Tests/Primer/v2/RawDataManagerValidationTests.swift
- Tests/Stripe/ACHMocks.swift
- Tests/Utilities/Mocks.swift
- Tests/Utilities/Mocks/Services/MockAPIClient.swift
- Tests/Utilities/Test Utilities/SDKSessionHelper.swift
Added support for Apple Pay MPAN. In order for Apple to return new token, we must pass exactly one additional payment request:
- deferred payment request
- automatic reload payment request
- recurring payment request
> feat(Apple Pay): Added support for MPAN

- Sources/PrimerSDK/Classes/Modules/ImageManager.swift
- Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
- Tests/Primer/Modules/ImageFileTests.swift
- Tests/Primer/Modules/ImageManagerTests.swift
Fixes console noise error `[invalid-value] Invalid value nil for key remoteUrl` reported by GlassesUSA in ESC-481.
When payment methods don't have remote icon URLs, ImageManager attempts to download files with nil `remoteUrl`, causing unnecessary error logging.
- Add early checks in `getImage()` methods to skip download when:
- Image already exists (cached or bundled)
- remoteUrl is nil
- Uses idiomatic Swift `guard` statements for consistency
- Eliminates console noise for valid use cases
- No functional changes - bundled and base64 images continue to work as before
- Cleaner logs for merchants
Fixes: ESC-481
> fix: Reduce console noise for nil remoteUrl in ImageManager

- Sources/PrimerSDK/Classes/Core/Primer/PrimerDelegate.swift
- Sources/PrimerSDK/Classes/Extensions & Utilities/StringExtension.swift
- Tests/Primer/Extensions/StringExtensionTests.swift
- Tests/Primer/Managers/PrimerBancontactCardDataManagerTests.swift
- Tests/Primer/Managers/PrimerRawCardDataManagerTests.swift
- Tests/Primer/Utils/DateTests.swift
- Tests/Primer/v2/RawDataManagerValidationTests.swift
This PR adds support for MM/YY expiry date format in the Headless SDK's RawDataManager, addressing the format inconsistency between Drop-in UI (MM/YY) and Headless (MM/YYYY) implementations.
Get Your Guide (GYG) reported that our SDK has an inconsistency:
- **Drop-in UI**: Uses MM/YY format for expiry dates
- **Headless/RawDataManager**: Uses MM/YYYY format
This discrepancy was blocking GYG's A/B experiment, as they need consistent validation logic across both their native form and Primer's form.
Modified the `validateExpiryDateString()` function to accept both MM/YY and MM/YYYY formats:
- Detects format based on year component length (2 vs 4 digits)
- Converts MM/YY to MM/YYYY internally by adding "20" prefix
- Maintains backward compatibility for existing MM/YYYY users
- Updated …
> feat: Add support for MM/YY expiry date format in RawDataManager

- Sources/PrimerSDK/Classes/Error Handler/ErrorHandler.swift
- Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift
This will now print out the caller name, function, line etc at the error handling level (as opposed to the past userInfo level)
> refactor: Log caller info in handled usage

- Debug App/Resources/Localized Views/Base.lproj/Main.storyboard
- Debug App/Sources/Extension/ViewController+Primer.swift
- Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
- Removes the APIVersion segmented control from the Debug App UI
- Fixes a build issue from a remaining `.v2` reference
> fix: Remove APIVersion control from Debug App UI

- fastlane/Fastfile
Tag the release and nightly builds with static custom IDs, to more easily target those when running UI tests from e2e-tests repo.
> ci: Correctly tag release and nightly builds
