primer-io/primer-sdk-ios

README.md
CHE-366
Updates documentation link
None
_QA_
=> CHE-366 Update documentation link

Example/PrimerSDK.xcodeproj/project.pbxproj, Example/PrimerSDK/Base.lproj/Main.storyboard, Example/PrimerSDKExample_UITests/Base.swift, Example/PrimerSDKExample_UITests/PrimerSDKExample_UITests.swift, Example/PrimerSDKExample_UITests/UniversalCheckout.swift, Example/PrimerSDKExample_UITests/Vault.swift, Example/PrimerSDKExample_UITests/VaultKlarna.swift, Sources/PrimerSDK/Classes/User Interface/Root/Route.swift
CHE-797
Adds UI tests for the vault flow
n/a
_QA_
=> Feature/che 797 UI test vault

Example/PrimerSDK/MerchantCheckoutViewController.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift
CHE-
Adds unique error codes on PrimerError and KlarnaException so they can be distinguished.
n/a
_QA_
=> CHE-855 Fix user cancelled error code

Example/Pods/Pods.xcodeproj/project.pbxproj
=> Fix build failure in Exampe project

Sources/PrimerSDK/Classes/Core/Payment Services/PaymentMethodConfigService.swift, Sources/PrimerSDK/Classes/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/User Interface/Checkout/VaultCheckoutViewController.swift, Sources/PrimerSDK/Classes/User Interface/OAuth/OAuthViewController.swift, Sources/PrimerSDK/Classes/User Interface/OAuth/OAuthViewModel.swift, Sources/PrimerSDK/Classes/User Interface/OAuth/PrimerWebViewController.swift, Sources/PrimerSDK/Classes/User Interface/Root/RootViewController.swift, Sources/PrimerSDK/Classes/User Interface/Root/Route.swift
Updates the payment flow to include Apaya. Created a new base class abstraction for webviews so that we can easily add more similar payment flows in the future.
=> add apaya flow

Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDK.xcodeproj/project.pbxproj, Example/PrimerSDK/MerchantCheckoutViewController.swift, Sources/PrimerSDK/Classes/Data Models/Currency.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/IntExtension.swift, Sources/PrimerSDK/Classes/User Interface/Checkout/VaultCheckoutViewModel.swift, Tests/PrimerSDK_Tests/Utils/IntExtensionTests.swift
CHE-
The amount string in the main checkout view displayed incorrectly for some currencies.
Fixed this + added some unit tests
_QA_
=> Fix Amount String

PrimerSDK.podspec
=> Hotfix v.1.12.2

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfig.swift
Hotfix 1.12.3
Fixes config parsing for unknown payment methods.
=> Hotfix 1.12.3

PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/Apple Pay/ApplePayViewModel.swift
Hotfix 1.13.2
Fixes Apple Pay showing an error
=> Hotfix 1.13.2

Example/PrimerSDK/AppViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApayaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ExternalPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PayPalTokenizationViewModel.swift
Release 1.14.1
Fix bug on `tokenAddedToVault()`
=> Release 1.14.1

Example/PrimerSDK/MerchantCheckoutViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfig.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift
Hotfix 1.14.3
Fixes crash when flow is presented and nullified.
Exposes `PrimerError` and `ApayaException`
=> Hotfix 1.14.3

Example/PrimerSDK/MerchantCheckoutViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/Root/PrimerNavigationController.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormTokenizationViewModel.swift
Hotfix 1.15.1
Fix broken case, and its presentation.
=> Hotfix 1.15.1

Sources/PrimerSDK/Classes/User Interface/OAuth/PrimerWebViewController.swift
DEX-835
Constraints webview to safe layout guide.
_QA_
=> DEX-835 Fix Apaya status bar issue

Example/PrimerSDK/AppViewController.swift, Example/PrimerSDK/CreateClientToken.swift, Example/PrimerSDK/MerchantCheckoutViewController+Primer.swift, Example/PrimerSDK/MerchantCheckoutViewController.swift, Example/PrimerSDK/Networking.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/Banks/BankSelectorViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/BankSelectorTokenizationViewModel.swift, Tests/PrimerSDK_Tests/Primer/PrimerTests.swift, Tests/PrimerSDK_Tests/Services/PaymentMethodConfigServiceTests.swift
Release 1.19.1
- Fix buggy behaviour on Bank based APMs.
- Align example app API calls with cloud functions.
=> Release 1.19.1

PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApayaTokenizationViewModel.swift
Release 1.19.3
- Fixes Apaya redirection for subdomains
=> Release 1.19.3

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Payment Services/ClientTokenService.swift, Sources/PrimerSDK/Classes/Data Models/ClientToken.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/StringExtension.swift
Release 1.19.4
- Fixes client token null values bug
=> Release 1.19.4

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Data Models/PrimerFlowEnums.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
Release 1.19.6
- Fix bug for default enum case.
- Do not print warning if settings have already been modified by the client session.
=> Release 1.19.6

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
Release 1.19.7
- Fix bug of replacing settings country code with client session's billing address country code.
=> Release 1.19.7

PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/Root/PrimerCardFormViewController.swift
Release 1.20.1
- Fixes card form view bug
=> Release 1.20.1

Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDK/Base.lproj/Main.storyboard, Example/PrimerSDK/MerchantCheckoutViewController.swift, Sources/PrimerSDK/Classes/Data Models/CheckoutModule.swift, Sources/PrimerSDK/Classes/Data Models/ClientSession.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfig.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/PostalCode.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/StringExtension.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/ZipCode.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerCardFormViewController.swift, Sources/PrimerSDK/Classes/User Interface/Text Fields/CardComponentsManager.swift, Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerNibView.swift, Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerPostalCodeFieldView.swift, Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerZipCodeFieldView.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormTokenizationViewModel.swift, Tests/PrimerSDK_Tests/Mocks/Mocks.swift, Tests/PrimerSDK_Tests/Services/PaymentMethodConfigServiceTests.swift, fastlane/Matchfile
* add dynamic zip code
* update test app
* update zip code action
* make minor fixes
* fix bug
* add simple zip localization
* update error message
DEX-
_QA_
=> Release 1.21.0

Sources/PrimerSDK/Classes/Core/Analytics/Device.swift
DEX-1092
Add locale in analytics
_QA_
=> DEX-1092 Add locale in device in analytics

Sources/PrimerSDK/Classes/Extensions & Utilities/BundleExtension.swift
DEX-1100
Fix RN bundle issue
_QA_
=> DEX-1100 Fix RN bundle issue

Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationType.swift
=> Make payment method type enum public

Example/PrimerSDK/Info.plist, Example/PrimerSDK/MerchantCheckoutViewController.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationOptions.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerUniversalCheckoutViewController.swift
DEX-1183
Fix deep linking for APMs
_QA_
=> Feature DEX-1183 Fix deep linking

Example/PrimerSDK/Info.plist, Example/PrimerSDK/MerchantCheckoutViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationOptions.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
Release 1.25.0
- Fix deep linking
=> Release 1.25.0

.gitmodules, Package.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Analytics/Device.swift, Sources/PrimerSDK/Classes/Core/Connectivity/Connectivity.swift, Sources/PrimerSDK/Classes/Core/Constants/Colors.swift, Sources/PrimerSDK/Classes/User Interface/PaymentMethodsGroupView.swift
Release 1.27.1
- Remove submodule
- Make License file a resource
- Fix SPM import errors
=> Release 1.27.1

Example/PrimerSDK/MerchantCheckoutViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Data Models/ClientToken.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationOptions.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodToken.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodTokenizationRequest.swift, Sources/PrimerSDK/Classes/Error Handler/ErrorHandler.swift, Sources/PrimerSDK/Classes/Mocks/MockPrimerAPIClient.swift, Sources/PrimerSDK/Classes/Services/API/Primer/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/Text Fields/CardComponentsManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApayaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/BankSelectorTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ExternalPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PayPalTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/QRCodeTokenizationViewModel.swift, Tests/PrimerSDK_Tests/Services/CardComponentManagerTests.swift
Release 1.27.3
- Fix UIWindow + UIScenes bug
- Add `isAlreadyVaulted` flag
- Fix warnings
- Connect analytics endpoint
=> Release 1.27.3

PrimerSDK.podspec, fastlane/Appfile, fastlane/Matchfile
=> Test Release 1.27.6

HeadlessUniversalCheckoutExample/HeadlessUniversalCheckoutExample/User Interface/PayViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Primer/PrimerDelegate.swift
Release 1.28.0-beta.4
- Fixes resume handler not getting called
=> Release 1.28.0-beta.4

Sources/PrimerSDK/Classes/Data Models/PaymentMethodTokenizationRequest.swift, Sources/PrimerSDK/Classes/User Interface/Text Fields/CardComponentsManager.swift
Changes multi use tokens to single use tokens.
=> Hotfix on multi use token

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckoutProtocols.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/UILocalizableUtil.swift, Sources/PrimerSDK/Classes/User Interface/Identifiable.swift
Hotfix 1.29.1
- Minor bug fixes
=> Hotfix 1.29.1

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ExternalPaymentMethodTokenizationViewModel.swift
- Modify the get assets API to accomodate RN
- Throw event when APM is presented.
=> Release 1.28.0 beta.5

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Primer/AppState.swift
Release 1.30.1
- Modify accessibility of RN implemented callbacks flags
=> Release 1.30.1

Example/PrimerSDK/AppViewController.swift, Example/PrimerSDK/MerchantCheckoutViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/BankSelectorTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
Release 1.32.2
- Fixes Klarna vaulting tokenization failing
- Fixes ingoring interaction events on Dot Pay
=> Release 1.32.2

Example/PrimerSDK/AppViewController.swift, Example/PrimerSDK/MerchantCheckoutViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/BankSelectorTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
=> Release 1.28.0 beta.8

PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/Text Fields/PrimerCardholderNameFieldView.swift
Release 1.32.3
- Fix cardholder field backspace not working
=> Release 1.32.3

Example/Pods/Pods.xcodeproj/project.pbxproj, Example/PrimerSDK/AppViewController.swift, Example/PrimerSDK/MerchantCheckoutViewController.swift, Example/PrimerSDK_Example.entitlements, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Data Models/VaultCheckoutViewModel.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/UINavigationController+Extensions.swift, Sources/PrimerSDK/Classes/Strings.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerNavigationController.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerUniversalCheckoutViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
Release 1.32.5
- Fixes Apple Pay cancellation flow
- Replaces primer error message on primer's error view with a generic message
=> Release 1.32.5

Example/PrimerSDK/AppViewController.swift, Example/PrimerSDK/MerchantCheckoutViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Data Models/ClientSession.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
Release 1.33.1
- Fixes Apple Pay with merchant & items' name
=> Release 1.33.1

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Extensions & Utilities/UINavigationController+Extensions.swift
Release 1.33.2
- Fix import for SPM
=> Release 1.33.2

Sources/PrimerSDK/Classes/Data Models/PrimerConfiguration.swift
DEX-1802
Remove apple pay view model if it cannot make payments
=> DEX-1802 Remove apple pay view model if it cannot make payments

Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDK.xcodeproj/project.pbxproj, Example/PrimerSDK/AppViewController.swift, Example/PrimerSDK/Base.lproj/Main.storyboard, Example/PrimerSDK/MerchantCardFormViewController.swift, Example/PrimerSDK/MerchantCheckoutViewController.swift, Example/PrimerSDK/MerchantPaymentMethodsViewController.swift, Example/PrimerSDK/Networking.swift
- Added the possibility to inject the API-KEY before initializing the SDK. First TextField from the top.
- Updated example app project settings
=> DEX-1744 injectable api key

Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDKExample_UITests/UniversalCheckout.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift
Release 1.34.2
- Hotfix Apple Pay, Card, Apaya and Paypal crash when presented directly
=> Release 1.34.2

Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDK.xcodeproj/project.pbxproj, Example/PrimerSDK/AppViewController.swift, Example/PrimerSDKExample_UITests/Base.swift, Example/PrimerSDKExample_UITests/UniversalCheckout+PrimerTestPaymentMethods.swift, Example/PrimerSDKExample_UITests/UniversalCheckout.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfiguration.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationOptions.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationType.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodTokenizationRequest.swift, Sources/PrimerSDK/Classes/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Strings.swift, Sources/PrimerSDK/Classes/User Interface/Components/HeaderFooterLabelView.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/TestPaymentMethods/FlowDecisionTableViewCell.swift, Sources/PrimerSDK/Classes/User Interface/TestPaymentMethods/PrimerTestPaymentMethodViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ExternalPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PrimerTestPaymentMethodTokenizationViewModel.swift
=> DEX-1821 Dummy APMs

Example/PrimerSDK/AppViewController.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationType.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodTokenizationRequest.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
Releasen 1.36.1
- Apply Klarna checkout fix
- Apply minor HUC changes
=> Releasen 1.36.1

Example/PrimerSDK/AppViewController.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationType.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodTokenizationRequest.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
DEX-1946
- Fixes Klarna checkout
- Applies minor changes on presenting PM from HUC
=> Feature DEX 1946 Fix Klarna checkout

Contributing.md, README.md
This PR adds the contributing file to our Github README
=> Adding Contributing file

Example/PrimerSDK.xcodeproj/xcshareddata/xcschemes/PrimerSDK-Example.xcscheme, Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/Logger.swift, Sources/PrimerSDK/Classes/Services/Network/URLSessionStack.swift
DEX-2019
- Add a scheme flag to silence analytics logs
=> DEX-2019 analytics log flag

Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Sources/PrimerSDK/Classes/Modules/PollingModule.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ExternalPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/QRCodeTokenizationViewModel.swift
DEX-2052
- [Refactor] Create a polling module
=> DEX-2052 Create a polling module and use it in redirect APMs

.github/workflows/build_test_upload.yml, fastlane/Fastfile
I'm re-enabling the Firebase upload based on the latest pipelines' updates
=> DEX-2178  Re-enabled firebase upload

.github/workflows/build_test_upload.yml, fastlane/Fastfile
I'm re-enabling the Firebase upload based on the latest pipelines' updates
=> DEX-2178  Re-enabled firebase upload (#429)

Sources/PrimerSDK/Classes/Data Models/PaymentMethodToken.swift, Sources/PrimerSDK/Classes/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerUniversalCheckoutViewController.swift
DXS-5
Fix paying with a vaulted payment method for PayPal and Klarna
=> Hotfix on vaulted payment methods

Sources/PrimerSDK/Classes/Core/Constants/Dimensions.swift, Sources/PrimerSDK/Classes/Core/Constants/Strings.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/PrimerButton.swift, Sources/PrimerSDK/Classes/Modules/UserInterfaceModule.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerNavigationBar.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormsTokenizationViewModel/CardFormPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift
- Reviewed PrimerNavagationBar
- Removed `isTokenizing` check. Now relying on button animation
=> Hotfix/prepare release 2.4.0

Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDK.xcodeproj/project.pbxproj, Example/PrimerSDK/AppViewController.swift, Example/PrimerSDK/Base.lproj/Main.storyboard, Example/PrimerSDK/MerchantHUCRawCardDataViewController.swift, Example/PrimerSDKExample_UITests/Base.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckoutProtocols.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawData.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawDataManager.swift, Sources/PrimerSDK/Classes/Core/Primer/DependencyInjection.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/Modules/UserInterfaceModule.swift, Sources/PrimerSDK/Classes/User Interface/Components/PrimerResultViewController.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/BankSelectorTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormsTokenizationViewModel/Fields/CardholderNameField.swift, Tests/PrimerSDK_Tests/Mocks/Mocks.swift, Tests/PrimerSDK_Tests/PrimerHeadlessUniversalCheckout/PrimerRawDataManagerTests.swift, Tests/PrimerSDK_Tests/Services/PayPalServiceTests.swift, Tests/PrimerSDK_Tests/Services/PaymentMethodConfigServiceTests.swift, Tests/PrimerSDK_Tests/ViewModels/VaultCheckoutViewModelTests.swift
- Headless Checkout Raw Data handling
- Codebase improvements
- UI Tests improvements
=> Release 2.5.0

Example/Podfile, Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDK.xcodeproj/project.pbxproj, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Data Models/PrimerConfiguration.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
DEX-2335
Replaces Klarna webview with Klarna 1 SDK
=> Feature DEX 2335 klarna in app v1

Sources/PrimerSDK/Classes/Core/Primer/PrimerDelegate.swift, Sources/PrimerSDK/Classes/Data Models/PaymentAPIModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift
Renaming `PrimerCheckoutResultData` into `PrimerCheckoutAdditionalInfo`
=> PrimerCheckoutAdditionalInfo rename

Example/Podfile, Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Example/PrimerSDK.xcodeproj/project.pbxproj, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Data Models/PrimerConfiguration.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
Release 1.37.0
- Replace Klarna webview with Klarna's SDK
=> Release 1.37.0

Example/Pods/Pods.xcodeproj/project.pbxproj, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Data Models/Notification.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ExternalPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel.swift
DEX-2436
- Push to loading screen on web redirect when redirected back to the app or loading spinner gets presented
=> DEX-2436 Fix done cancellation

Dangerfile.swift
=> DEX-2462 danger updates

Sources/PrimerSDK/Classes/Core/Constants/Strings.swift, Sources/PrimerSDK/Classes/Data Models/VoucherValue.swift, Sources/PrimerSDK/Classes/Modules/UserInterfaceModule.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerAccountInfoPaymentViewController.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerRootViewController.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerVoucherInfoPaymentViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel+FormViews.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift
- Added the possibility of handling Multibanco with its UI flow
- Reviewed responsibility of specific functions of the FormTokenizationViewModel
- Implemented **Share** option for the Voucher Info View via ActivityViewController
- Minor codebase review
=> CHKT-15 Multibanco via Adyen UI

Sources/PrimerSDK/Classes/Data Models/Klarna.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
DEVX-205
Replace `hppRedirectUrl` with `urlScheme`
=> DEVX-205 Replace Klarna redirect URL

Example/Podfile, Example/Podfile.lock, Example/Pods/Local Podspecs/PrimerSDK.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/PrimerSDK/PrimerSDK-Info.plist, Example/Pods/Target Support Files/PrimerSDK/ResourceBundle-PrimerResources-PrimerSDK-Info.plist, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckoutUIManager.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawDataManager.swift, Sources/PrimerSDK/Classes/Core/Payment Services/ClientTokenService.swift, Sources/PrimerSDK/Classes/Data Models/PrimerConfiguration.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/TimerExtension.swift, Sources/PrimerSDK/Classes/Modules/ClientSessionActionsModule.swift, Sources/PrimerSDK/Classes/Modules/Downloader.swift, Sources/PrimerSDK/Classes/PCI/Services/Network/URLSessionStack.swift, Sources/PrimerSDK/Classes/PCI/User Interface/CardComponentsManager.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/CheckoutWithVaultedPaymentMethodViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift, Tests/PrimerSDK_Tests/Mocks/Services/ClientTokenService.swift
* Refactor client token service
* Replace existing files and don't end with error
* Avoid client session actions request if not needed
* Omit API token validation at certain times
* Bump
* Request config without display metadata
* Add timer delay promise
* Bump
* Cache images manually
* Add user info on errors
* Update Example/Podfile
Co-authored-by: Dario Carlomagno <dario@primer.io>
* Remove comment
Co-authored-by: Evangelos Pittas <evangelos@primer.io>
Co-authored-by: Dario Carlomagno <dario@primer.io>
DEX-
_QA_
=> DXS-76 (#488)

Internal/Debug App/Tests/Unit Tests/Modules/DropInUI_TokenizationViewModelTests.swift, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerDelegate.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift
=> Refactor delegate

Sources/PrimerSDK/Classes/Core/Constants/Strings.swift
The copy now reflects the intention of the vaulted payment methods.
=> CHKT-182 Fix copy based on vault intent

Sources/PrimerSDK/Classes/Modules/UserInterfaceModule.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerFormViewController.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerUniversalCheckoutViewController.swift
Solving the payment methods constraints issues
=> CHKT-185 payment methods constraints

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckoutUIManager.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawDataManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/CheckoutWithVaultedPaymentMethodViewModel.swift
Release 2.11.1
- Fix crash on HUC raw data manager with processor 3DS introduced on 2.11.0
=> Release 2.11.1

Sources/PrimerSDK/Classes/Core/Constants/Strings.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel+FormViews.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift
Fixing the Blik flow after tokenization.
=> Fixing the Blik flow

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Constants/Strings.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel+FormViews.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift
CHKT-223 Fixing the Blik flow (#533)
=> Release 2.13.1

Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift, Sources/PrimerSDK/Classes/PCI/TokenizationService.swift, Sources/PrimerSDK/Classes/PCI/User Interface/CardComponentsManager.swift
DEX-418
- Obsolete 3DS on vault setting
=> Feature/DEVX 418 deprecate 3DS vault

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawPhoneNumberDataTokenizationBuilder.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawRetailerDataTokenizationBuilder.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift, Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataRedirectTokenizationBuilder.swift, Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift, Sources/PrimerSDK/Classes/PCI/TokenizationService.swift, Sources/PrimerSDK/Classes/PCI/User Interface/CardComponentsManager.swift
- DEVX-418 obsolete 3DS vault
- DEX-2494 Card holder name fix
- DEX-2494  Fix delegate issue on Tokenization builder
=> Release 2.14.0

.github/workflows/build_test_upload.yml, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PayPalTokenizationViewModel.swift
DXS-127 Fix Paypal service (#542)
=> Release 2.14.1

PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/3DS/3DSService.swift, Sources/PrimerSDK/Classes/Core/Analytics/Analytics.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckoutUIManager.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawDataManager.swift, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerSource.swift, Sources/PrimerSDK/Classes/Data Models/PrimerIntegrationOptions.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/BundleExtension.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/CardFormPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/CheckoutWithVaultedPaymentMethodViewModel.swift
Release 2.14.2
- Fix 3DS on frictionless flows
- Fix Analytics events
=> Release 2.14.2

PrimerSDK.podspec
=> DEVX-521 Generate Info.plist

Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift
=> CHKT-314 Cardholder name check fix

Internal/Debug App/Podfile, Internal/Debug App/Project.swift, Internal/Debug App/tuist-generate.sh, PrimerSDK.podspec, README.md, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/PCI/Checkout Components/PrimerRawCardDataTokenizationBuilder.swift
- CHKT-287 Contributing link fix
- DEVX-521 added the `GENERATE_INFOPLIST_FILE` as part of the `xcconfig` of the `PrimerSDK` podspec 
- CHKT-314 Cardholder Name fix
- Minor updates to README.md
- Renamed Internal Debug App alongside minor updates
=> Release 2.15.0

Internal/Debug App/Podfile, Internal/Debug App/Tests/Unit Tests/Mocks.swift, PrimerSDK.podspec, Sources/PrimerSDK/Classes/Core/Analytics/Analytics.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerHeadlessUniversalCheckoutUIManager.swift, Sources/PrimerSDK/Classes/Core/Checkout Components/PrimerRawDataManager.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerDelegate.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift, Sources/PrimerSDK/Classes/Data Models/ClientToken.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethod.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethodConfigurationOptions.swift, Sources/PrimerSDK/Classes/Data Models/PrimerConfiguration.swift, Sources/PrimerSDK/Classes/Data Models/PrimerPaymentMethodType.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSDKIntegrationType.swift, Sources/PrimerSDK/Classes/Data Models/TokenizationRequestPaymentInstrument.swift, Sources/PrimerSDK/Classes/Data Models/TokenizationRequestPaymentSessionInfo.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/Modules/PollingModule.swift, Sources/PrimerSDK/Classes/Modules/UserInterfaceModule.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/CheckoutWithVaultedPaymentMethodViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/IPay88TokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
Release 2.16.0
- Integrate iPay88
- Add Headless analytics events
- Add properties in analytics events
- Return error on Apple Pay on simulator
=> Release 2.16.0

PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
Release 2.16.1
Change Klarna's vault payment category
=> Release 2.16.1

Internal/Debug App/Tests/Unit Tests/Data Models/PaymentMethodConfigTests.swift, Internal/Debug App/Tests/Unit Tests/Data Models/PrimerCheckoutTheme.swift, Internal/Debug App/Tests/Unit Tests/Mocks.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift
CHKT-1007 Fix styling
Fix styling not injected
=> CHKT-1007 Fix styling

Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift
Nullify root vc after resigning key window
=> CHKT-1130 fix unbalanced begin end appearance transitions warning

Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift
Flat map analytics request `data` field
=> CHKT-1127 Flat map analytics request `data` field

Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift
Add checkout session id in requests' headers
=> CHKT-1127 Add checkout session id in headers

Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift, Sources/PrimerSDK/Classes/Data Models/Notification.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/WebRedirectPaymentMethodTokenizationViewModel.swift
Implement deep link cancellation logic
=> CHKT-1096 cancellation deeplinks

Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift, Sources/PrimerSDK/Classes/Data Models/Notification.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/WebRedirectPaymentMethodTokenizationViewModel.swift
Refactor cancellation deeplink logic
=> CHKT-1120 fix atome cancellation

Internal/Debug App/Resources/Localized Views/Base.lproj/Main.storyboard, Internal/Debug App/Sources/Model/TestScenario.swift, Internal/Debug App/Sources/Network/Networking.swift, Internal/Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift, Internal/Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift, Sources/PrimerSDK/Classes/Data Models/Notification.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/IPay88TokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/WebRedirectPaymentMethodTokenizationViewModel.swift
=> CHKT-1108 UI tests

Internal/Debug App/Resources/Localized Views/Base.lproj/Main.storyboard, Internal/Debug App/Sources/Model/TestScenario.swift, Internal/Debug App/Sources/Network/Networking.swift, Internal/Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift, Internal/Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift, Sources/PrimerSDK/Classes/Data Models/Notification.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/IPay88TokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/WebRedirectPaymentMethodTokenizationViewModel.swift
=> CHKT-1057 iPay88 validation

Internal/Debug App/Resources/Localized Views/Base.lproj/Main.storyboard, Internal/Debug App/Sources/Model/TestScenario.swift, Internal/Debug App/Sources/Network/Networking.swift, Internal/Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift, Internal/Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsEvent.swift, Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsService.swift, Sources/PrimerSDK/Classes/Core/Primer/PrimerInternal.swift, Sources/PrimerSDK/Classes/Data Models/Notification.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift, Sources/PrimerSDK/Classes/User Interface/PrimerUIManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/IPay88TokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/WebRedirectPaymentMethodTokenizationViewModel.swift
=> CHKT-1056 Add analytics events

Sources/PrimerSDK/Classes/Modules/Downloader.swift
- Fix scenario where API request returns cache data but image file does not exist
=> CHKT-1178 fix cached data without file

Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/Payment Method Managers/CardComponentsManager.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/Payment Method Managers/RawDataManager.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/CheckoutWithVaultedPaymentMethodViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
- Throw a console warning if `decisionHanlder` is not called within 5 sec
=> CHKT-1175 throw warning when decision handler is not called

Internal/Debug App/Sources/View Controllers/MerchantHeadlessCheckoutAvailablePaymentMethodsViewController.swift, Sources/PrimerSDK/Classes/Core/Analytics/AnalyticsEvent.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/AssetsManager.swift, Sources/PrimerSDK/Classes/Data Models/PaymentMethod.swift
- Add `paymentMethodName` on asset
=> CHKT-1153 add payment method name on asset

Internal/Debug App/Sources/Model/TestScenario.swift, Internal/Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/IPay88TokenizationViewModel.swift
=> CHKT-1220 Change ipay88 validation

Internal/Debug App/Tests/Unit Tests/v2/HeadlessUniversalCheckoutTests.swift, Sources/PrimerSDK/Classes/Core/Payment Services/PrimerAPIConfigurationModule.swift
- Always refetch config on `start`
=> CHKT-1239 Remove fetch if needed

Internal/Debug App/Tests/Unit Tests/Data Models/TokenizationResponseTests.swift, Internal/Debug App/Tests/Unit Tests/v2/HeadlessUniversalCheckoutTests.swift, Sources/PrimerSDK/Classes/Core/Payment Services/PrimerAPIConfigurationModule.swift, Sources/PrimerSDK/Classes/Data Models/TokenizationResponse.swift, Sources/PrimerSDK/Classes/User Interface/Root/PrimerUniversalCheckoutViewController.swift
=> Hotfix - Map missing tokenization data

Internal/Debug App/Tests/Unit Tests/Data Models/ApplePayTests.swift, Sources/PrimerSDK/Classes/Core/Constants/Strings.swift, Sources/PrimerSDK/Classes/Data Models/ClientSession.swift, Sources/PrimerSDK/Classes/Data Models/OrderItem.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
- Take into account tax and discount on Apple Pay items
- Prioritize merchant amount over total amount
- Only take into account surcharge when merchant amount is not set
=> CHKT-1263 Apple pay Discount

Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
- Access vc only on `DEBUG` mode
=> CKT-1314 Fix Klarna archiving issue

Internal/Debug App/Tests/Unit Tests/Data Models/PayPalConfirmBillingAgreementTests.swift, Sources/PrimerSDK/Classes/Data Models/PayPal.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
- Make `shippingAddress` optional
=> CHKT-1309 Fix PayPal vaulting

Sources/PrimerSDK/Classes/Modules/UserInterfaceModule.swift
=> Fixed payment method button text not being presented

Internal/Debug App/Resources/Localized Views/Base.lproj/Main.storyboard, Internal/Debug App/Sources/View Controllers/MerchantCheckoutViewController.swift, Internal/Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Internal/Debug App/Tests/Unit Tests/Primer/PrimerRawCardDataManagerTests.swift, Internal/Debug App/Tests/Unit Tests/v2/RawDataManagerTests.swift, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
- Reintroduce `showPaymentMethod` on the dropin
=> CHKT-1311 Reintroduce show payment method

Internal/Debug App/Podfile, Internal/Debug App/Resources/Localized Views/Base.lproj/Main.storyboard, Internal/Debug App/Sources/Network/Networking.swift, Internal/Debug App/Sources/View Controllers/MerchantCheckoutViewController.swift, Internal/Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Internal/Debug App/Tests/Unit Tests/Primer/PrimerRawCardDataManagerTests.swift, Internal/Debug App/Tests/Unit Tests/v2/RawDataManagerTests.swift, Sources/PrimerSDK/Classes/Core/3DS/3DSService.swift, Sources/PrimerSDK/Classes/Core/Primer/Primer.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/Payment Method Managers/CardComponentsManager.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/Payment Method Managers/RawDataManager.swift, Sources/PrimerSDK/Classes/Data Models/TokenizationResponse.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/CheckoutWithVaultedPaymentMethodViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
=> CHKT-1335 Fix vaulted payment method token data regression

Internal/Debug App/Appetize Podfile/Podfile, Internal/Debug App/Podfile, Internal/Debug App/Project.swift, fastlane/Fastfile
=> Updated livedemostore host needed for Appetize preview, fixed Tuist project creation

Internal/Debug App/Podfile, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/IPay88TokenizationViewModel.swift
JIRA [Update iPay88 version](https://primerapi.atlassian.net/browse/CHKT-1425)
Currently pointing to master branch, should be merged after 2.17.0 release
=> CHKT-1425 iPay88 update

Internal/Debug App/ExampleApp.entitlements, Internal/Debug App/Info.plist
=> chore: Enabled app links for livedemostore

Internal/Debug App/ExampleApp.entitlements, Internal/Debug App/Info.plist, Internal/Debug App/Podfile, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel.swift
This release contains 2 changes:
- Apple Pay force unwrap optional crash fix
- Support for the app links for livedemostore as an example
- force Light mode in DebugApp
=> Release 2.17.1

Example/Podfile, Example/Primer.io Example App.xcodeproj/project.pbxproj, Example/Resources/Localized Views/Base.lproj/Main.storyboard, Example/Resources/Localized Views/en.lproj/Main.strings, Example/Sources/Network/Networking+Models.swift, Example/Sources/View Controller/MerchantAssetsViewController.swift, Example/Sources/View Controller/MerchantCardFormViewController.swift, Example/Sources/View Controller/MerchantHUCRawCardDataViewController.swift, Example/Sources/View Controller/MerchantPaymentMethodsViewController.swift, Internal/Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift
CHKT-1637
The example app doesn't build currently. This fixes the build issues and gets the basic functionality of the app working again.
_QA_
=> Update example app

Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift
CHKT-1690
Fixes a build error when building the SDK with Xcode 15.
_QA_
=> Fix build error when building with Xcode 15 / for iOS 17

Debug App/Tests/Unit Tests/Network/URLSessionStackTests.swift, Sources/PrimerSDK/Classes/PCI/Services/Network/URLSessionStack.swift
CHKT-1717
Please see ticket for details
_QA_
=> Filter out events for analytics endpoint network requests + unit test

Debug App/Primer.io Debug App.xcodeproj/project.pbxproj, Debug App/Sources/View Controllers/New UI/MerchantHeadlessCheckoutNolPayViewController.swift, Debug App/Tests/Unit Tests/Mocks.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolPayLinkCardComponentTest.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolPayLinkedCardsComponentTests.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolPayPaymentComponentTests.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolPayPhoneMetadataServiceTests.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolPayUnlinkCardComponentTest.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolTestsMocks.swift, Debug App/Tests/Unit Tests/Primer/NolPay/PrimerHeadlessNolPayManagerTests.swift, Debug App/Tests/Unit Tests/Utils/DebouncerTests.swift, Debug App/Tests/Unit Tests/v2/MockAPIClient.swift, Sources/PrimerSDK/Classes/Core/Payment Services/CreateResumePaymentService.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayAnalyticsEvents.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayLinkCardComponent.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayLinkedCardsComponent.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayPaymentComponent.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayPhoneMetadataService.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/NolPay/NolPayUnlinkCardComponent.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Composable/PrimerHeadlessComposable.swift, Sources/PrimerSDK/Classes/Data Models/PhoneMetadataDataRequest.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerValidationError.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/Debouncer.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/StringExtension.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/Services/Network/PrimerAPIClient.swift
* Introduce async mobile number validation
_QA_
=> feat: Implement Phone Validation for Nol

.cz.toml, CHANGELOG.md, Sources/PrimerSDK/Classes/version.swift
=> Release 2.18.0

.github/workflows/ui-tests.yml, .github/workflows/xcode-versions-build.yml
Use `push` rather than pull request trigger
=> Run on push to release/

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.18.1 

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.18.2

Debug App/.swiftlint.yml, Debug App/Primer.io Debug App.xcodeproj/project.pbxproj, Sources/PrimerSDK/Classes/Core/Logging/PrimerLogger.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/UIDeviceExtension.swift, Sources/PrimerSDK/Classes/PCI/User Interface/Text Fields/PrimerTextField.swift, Sources/PrimerSDK/Classes/Third Party/PromiseKit/Dispatchers/RateLimitedDispatcher.swift, Sources/PrimerSDK/Classes/Third Party/PromiseKit/Wrappers/CatchWrappers.swift, Sources/PrimerSDK/Classes/Third Party/PromiseKit/Wrappers/RecoverWrappers.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
Make SwiftLint active as a RunPhase, disable rules, fix some warnings.
=> chore: Add SwiftLint as a Run Phase

.github/workflows/post-release-merge.yml
This PR creates a Github release as part of the post-release-merge flow
=> chore: adds release creation

Debug App/Podfile.lock
Per description. Prep for next release.
=> chore: Update 3DS and IPay88MY SDK version in debug app

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.18.3

Debug App/Tests/Unit Tests/Data Models/ThreeDSErrorTests.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolPayLinkedCardsComponentTests.swift, Debug App/Tests/Unit Tests/Primer/NolPay/NolPayPhoneMetadataServiceTests.swift, Sources/PrimerSDK/Classes/Core/3DS/3DSService.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/Payment Method Managers/CardComponentsManager.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/Payment Method Managers/RawDataManager.swift, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/Managers/VaultManager.swift, Sources/PrimerSDK/Classes/Error Handler/ErrorHandler.swift, Sources/PrimerSDK/Classes/Error Handler/Primer3DSErrorContainer.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerError.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerIPay88Error+Extension.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerInternalError.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerKlarnaError+Extension.swift, Sources/PrimerSDK/Classes/Error Handler/PrimerValidationError.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/PaymentMethodTypeProviding.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/CardFormPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/CheckoutWithVaultedPaymentMethodViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/IPay88TokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
CHKT-1993
- Adds `errorId` to context for all errors
- Adds `paymentMethodType` to context where applicable
=> fix: add additional info to errors

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.20.0

.cz.toml, .github/workflows/xcode-versions-build.yml, CHANGELOG.md, Debug App/Primer.io Debug App SPM.xcodeproj/project.pbxproj, Debug App/Primer.io Debug App.xcworkspace/xcshareddata/swiftpm/Package.resolved, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.20.1

.github/workflows/post-release-merge.yml
CHKT-XXXX
- Improves GH release generation.
Example: https://github.com/primer-io/primer-sdk-android/releases/tag/2.23.0
=> chore: improved release generation

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.21.0

Debug App/Podfile, Debug App/Podfile.lock, Debug App/Primer.io Debug App.xcworkspace/xcshareddata/swiftpm/Package.resolved, Debug App/Tests/Unit Tests/Extensions/StringExtensionTests.swift
This PR updates the 3DS version from 2.1.0 -> 2.2.0 in the Debug apps
=> chore: Update 3DS in Debug Apps

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.23.0

.github/actions/sonar/action.yml
CHKT-XXXX
- What do these changes do?
- Note any breaking changes and why they are necessary
=> chore: remove sonar properties log

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.26.4

.github/dependabot.yml
Adding `dependabot.yml` to keep our GH actions and dependencies up to date.
=> ci: added dependabot.yml

Debug App/ExampleApp.entitlements
Reverts primer-io/primer-sdk-ios#867
=> chore: Revert "chore: add acceptance merchant Ids"

Debug App/Primer.io Debug App.xcodeproj/project.pbxproj
Removes automatic signing to unblock UI tests
=> chore: remove automatic signing

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.26.6

.github/workflows/manual-translation-update.yml
This PR adds a new workflow for updating of the translations from Phrase.com
=> chore: Create manual-translation-update.yml

.github/workflows/manual-translation-update.yml
=> chore: Fine tune manual translations update workflow

.github/workflows/manual-translation-update.yml, phrase_config.yml
Fix PR making in the Manual Translations Update workflow
=> chore: Finish Manual Translation Workflow setup

.github/workflows/build-test-upload.yml, .github/workflows/ui-tests.yml
Updated Gitlab URL for mobile-appium-tests
Workflow run: https://github.com/primer-io/primer-sdk-ios/actions/runs/10096956151
=> ci(ui-tests): Updated Gitlab URL for mobile-appium-tests

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.29.0

Sources/PrimerSDK/Classes/PCI/Services/DefaultNetworkService.swift, Sources/PrimerSDK/Classes/PCI/Services/Network/Factories/NetworkRequestFactory.swift, Tests/Primer/Network/Factories/NetworkRequestFactoryTests.swift, Tests/Primer/Network/Services/NetworkingReportingServiceTests.swift
[JIRA](https://primerapi.atlassian.net/browse/ACC-3929)
Is this the right place for adding this header?
=> chore: Add new header field to every API call

Tests/Primer/Network/Factories/NetworkRequestFactoryTests.swift
Add more unit tests for the newly added header in API requests
=> chore: Add more tests

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.30.0

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.30.1

.cz.toml, .github/workflows/xcode-versions-build.yml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/User Interface/Components/PrimerCustomResult/PrimerResultPaymentStatusViewModel.swift, Sources/PrimerSDK/Classes/version.swift
=> Release 2.31.0

Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
This code was mistakenly left in on previous PR 😬 
CHKT-XXXX
- What do these changes do?
- Note any breaking changes and why they are necessary
=> chore: Remove mistakenly left in commented code

.github/workflows/ui-tests.yml
=> ci: add secret to manual ui tests flow

Debug App/Info.plist, Sources/PrimerSDK/Classes/Extensions & Utilities/DeeplinkUtils.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/WebRedirectPaymentMethodTokenizationViewModel.swift, Tests/Primer/Tokenization/View Models/WebRedirectPaymentMethodTokenizationViewModelTests.swift, Tests/Utilities/Mocks.swift
[ACC-4253](https://primerapi.atlassian.net/browse/ACC-4253)
[PRMSUP-2725](https://primerapi.atlassian.net/browse/PRMSUP-2725)
- Performs a check if the Vipps app is installed during the Vipps redirect flow - and falls back to the "WEB" implementation if the result is `false`
Use [this clientSession](https://livedemostore.common.primer.io/v2-latest/checkout?p=eyJjdXN0b21lcklkIjoiIiwibG9jYWxlIjoiIiwicGF5bWVudEZsb3ciOiJkZWZhdWx0IiwicHJvY2Vzc29yIjoiYnJhaW50cmVlIiwiY3VycmVuY3kiOiJOT0siLCJjb3VudHJ5Q29kZSI6Ik5PIiwidmFsdWUiOiIxMjAiLCJwcmVmZXJQYXlCeUNhcmRCdXR0b24iOmZhbHNlLCJ0aHJlZURTRW5hYmxlZCI6ZmFsc2UsImN1c3RvbWVyRGV0YWlsc0VuYWJsZWQiOnRydWUsInN1cmNoYXJnZUVuYWJsZWQiOmZhbHNlLCJwYXlwYWxTdXJjaGFyZ2UiOjAsImdvb2dsZVBheVN1cmNoYXJnZSI6MCwiYXBwbGVQYXlTdXJjaGFyZ2UiOjAsInBheXBhbFBheU5sU3VyY2hhcmdlIjowLCJpZGV …
=> fix: Fallback to Web flow when Vipps app is not installed

Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Tests/Primer/ApplePay/ApplePayPresentationManagerTests.swift, Tests/Primer/Tokenization/View Models/ApplePayTokenizationViewModelTests.swift
Removes references to private entities for now in Tests and Debug App
=> test: Remove ShippingOptions from tests and Debug App

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.31.1

Debug App/Podfile.lock, Sources/PrimerSDK/Classes/Core/PrimerHeadlessUniversalCheckout/PrimerHeadlessUniversalCheckout.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel+FormViews.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/PaymentMethodTokenizationViewModel+Logic.swift
CHKT-[4355](https://primerapi.atlassian.net/browse/ACC-4355)
- Forbid dismissal of the payment view mid tokenization and mid payment
[Test with Blik](https://www.notion.so/primerio/Testing-Adyen-APMs-926a703f134044d8b81069ae66db8a60?pvs=4#dbcad9f934984ac08b3e667d1d50cd3f)
=> fix: Adyen Blik dismissal issue and small UI glitch

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.31.2

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.31.3

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.32.0

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.32.1

Debug App/Podfile.lock, Package.resolved, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/KlarnaTokenizationViewModel.swift
[PRMSUP-3183](https://primerapi.atlassian.net/browse/PRMSUP-3183)
[PRMSUP-3183]: https://primerapi.atlassian.net/browse/PRMSUP-3183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Disable the close button for Klarna during payment processing

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.33.0

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.33.1

Sources/PrimerSDK/Resources/Localizable/ar.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/ca.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/da.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/de.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/el.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/en.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/es.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/fi-FI.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/fr.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/he.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/id.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/it.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/ko.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/lt-LT.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/ms.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/nb.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/nl.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/pl.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/pt.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/sl.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/sr-RS.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/sv.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/th.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/tr.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/uk-UA.lproj/Localizable.strings
This PR updates the translations from Phrase.com
=> chore: Translation Update

.github/workflows/manual-translation-update.yml, phrase_config.yml
Update Phrase config file to use Chinese
=> chore: Update phrase config file

Sources/PrimerSDK/Resources/Localizable/bg.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/cs.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/es-AR.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/es-MX.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/et.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/hr.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/hu.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/ja.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/lv.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/pt-BR.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/ro.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/ru.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/sk.lproj/Localizable.strings, Sources/PrimerSDK/Resources/Localizable/vi.lproj/Localizable.strings, phrase_config.yml
https://primerapi.atlassian.net/browse/ACC-3727
- Add support for:
•	Bulgarian
•	Czech
•	Spanish (Argentina)
•	Spanish (Mexico)
•	Estonian
•	Croatian
•	Hungarian
•	Japanese
•	Latvian
•	Portuguese (Brazil)
•	Romanian
•	Russian
•	Slovak
•	Vietnamese
- n/a
- n/a
=> feat: add missing localizations

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.35.0

Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/CardFormPaymentMethodTokenizationViewModel.swift
[JIRA](https://primerapi.atlassian.net/browse/PRMSUP-3173)
The removed piece of code NEVER WORKED and only created this bug, which has been here for around 3 years.
=> fix: Card Form for RTL languages

Sources/PrimerSDK/Classes/User Interface/Root/CVVRecapture/CVVRecaptureViewController.swift
[JIRA](https://primerapi.atlassian.net/browse/ACC-3527)
=> chore: Add a view appear event for CVV recapture

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.35.1

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.35.2

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.35.3

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.36.0

.github/actions/ui-tests/action.yml, .github/workflows/ui-tests.yml
Saves the app artifact and passes the link to UI tests for reporting
=> chore: add test link to UI Tests run

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.36.1

Debug App/Podfile.lock, Debug App/Resources/Localized Views/Base.lproj/Main.storyboard, Debug App/Sources/View Controllers/MerchantSessionAndSettingsViewController.swift, Sources/PrimerSDK/Classes/Data Models/PrimerSettings.swift, Sources/PrimerSDK/Classes/Modules/UserInterfaceModule.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/CardFormPaymentMethodTokenizationViewModel.swift, Tests/Primer/Modules/UserInterfaceModuleTests.swift, Tests/Primer/Tokenization/View Models/CardFormPaymentMethodTokenizationViewModelTests.swift
[CHKT-5364](https://primerapi.atlassian.net/browse/ACC-5364)
- Introduce a new optional `cardFormUIOptions` property on `PrimerUIOptions` to allow merchants to toggle the card-form pay button text.  
- Add `PrimerCardFormUIOptions` struct with a `payButtonAddNewCard: Bool` flag.  
- Decode/encode `cardFormUIOptions` in `PrimerUIOptions` so existing integrations remain unaffected when omitted.  
- Update `CardFormPaymentMethodTokenizationViewModel` and the `submitButton` factory to show **“Add new card”** (localized via `Strings.VaultPaymentMethodViewContent.addCard`) when:  
- `PrimerInternal.shared.intent == .checkout`  
- `uiOptions.cardFormUIOptions?.payButtonAddNewCard == true`  
- Otherwise, fall back to the default **“Pay $x.xx”** behavior.  
- Extend …
=> feat: Support Add New Card in card form flow

Sources/PrimerSDK/Classes/Data Models/CardNetwork.swift, Sources/PrimerSDK/Classes/PCI/Services/API/Primer/PrimerAPI.swift, Sources/PrimerSDK/Classes/PCI/Tokenization View Models/FormsTokenizationViewModel/FormPaymentMethodTokenizationViewModel.swift, Sources/PrimerSDK/Classes/Services/Network/Endpoint.swift
=> refactor: Remove unused code from Networking

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.38.0

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.38.2

Sources/PrimerSDK/Classes/Data Models/PrimerPaymentMethod.swift, Sources/PrimerSDK/Classes/Data Models/Theme/Public/PrimerThemeData+Deprecated.swift, Sources/PrimerSDK/Classes/Extensions & Utilities/ApplePayUtils.swift, Sources/PrimerSDK/Classes/Services/Network/WebAuthenticationService.swift, Sources/PrimerSDK/Classes/User Interface/TokenizationViewModels/ApplePayTokenizationViewModel.swift
We support >= 13.1 so these checks are not necessary
=> refactor: Remove redundant OS checks

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.39.2

.cz.toml, CHANGELOG.md, PrimerSDK.podspec, Sources/PrimerSDK/Classes/version.swift
=> Release 2.40.0
